# Form implementation generated from reading ui file 'first.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FirstTimeWindow(object):
    def setupUi(self, FirstTimeWindow):
        FirstTimeWindow.setObjectName("FirstTimeWindow")
        FirstTimeWindow.resize(296, 202)
        self.centralwidget = QtWidgets.QWidget(parent=FirstTimeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelTgId = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTgId.setObjectName("labelTgId")
        self.verticalLayout.addWidget(self.labelTgId)
        self.tgIdEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.tgIdEdit.setObjectName("tgIdEdit")
        self.verticalLayout.addWidget(self.tgIdEdit)
        self.CheckTg = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CheckTg.setObjectName("CheckTg")
        self.verticalLayout.addWidget(self.CheckTg)
        self.labelCode = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCode.setObjectName("labelCode")
        self.verticalLayout.addWidget(self.labelCode)
        self.codeEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.codeEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.codeEdit.setObjectName("codeEdit")
        self.verticalLayout.addWidget(self.codeEdit)
        self.submitBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submitBtn.setObjectName("submitBtn")
        self.verticalLayout.addWidget(self.submitBtn)
        FirstTimeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=FirstTimeWindow)
        self.statusbar.setObjectName("statusbar")
        FirstTimeWindow.setStatusBar(self.statusbar)

        self.retranslateUi(FirstTimeWindow)
        QtCore.QMetaObject.connectSlotsByName(FirstTimeWindow)

    def retranslateUi(self, FirstTimeWindow):
        _translate = QtCore.QCoreApplication.translate
        FirstTimeWindow.setWindowTitle(_translate("FirstTimeWindow", "First Time Setup"))
        self.labelTgId.setText(_translate("FirstTimeWindow", "Enter your Telegram ID:"))
        self.tgIdEdit.setPlaceholderText(_translate("FirstTimeWindow", "Telegram ID"))
        self.CheckTg.setText(_translate("FirstTimeWindow", "check tg"))
        self.labelCode.setText(_translate("FirstTimeWindow", "Enter the Code:"))
        self.codeEdit.setPlaceholderText(_translate("FirstTimeWindow", "Code"))
        self.submitBtn.setText(_translate("FirstTimeWindow", "Submit"))
